name: Deploy React App para GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Exibir variáveis de ambiente para depuração
        run: |
          echo "Firebase Config Debug:"
          echo "API Key: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}"
          echo "Auth Domain: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}"
          echo "Project ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}"
          echo "Storage Bucket: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}"
          echo "Messaging Sender ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}"
          echo "App ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}"

      - name: Instalar dependências
        run: npm install

      - name: Build
        run: npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}

      - name: Upload dos arquivos de build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy para o GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}